version: '3.8'

services:
  mtg-table:
    build: .
    container_name: mtg_web_canvass
    volumes:
      - mtg_data:/app/data
    ports:
      - "8087:8087"
    restart: unless-stopped

volumes:
  mtg_data:
